version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
      exclude:
        - gds-api-adapters
        - govuk_app_config
        - govuk_document_types
        - govuk_message_queue_consumer
        - govuk_schemas
        - govuk_sidekiq
        - plek
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    ignore:
      - dependency-name: ruby
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
