require "spec_helper"

RSpec.describe LearnToRank::ExplainScores do
  include Fixtures::LearnToRankExplain

  subject(:explainer) { described_class.new(explain) }
  let(:explain) { default_explanation }
  let(:scores) do
    {
      title_score: 125.71911880000002,
      description_score: 61.249814,
      all_searchable_text_score: 5.6863167,
      indexable_content_score: 33.8111188,
    }
  end

  context "when the explain score is empty" do
    let(:explain) { {} }

    describe "#title_score" do
      it "returns zero as the default" do
        expect(explainer.title_score).to eq(0)
      end
    end
  end

  describe "autogenerated score methods" do
    described_class::PERMITTED_FIELDS.each do |method|
      it "expects the #{method} method to have a test" do
        expect(scores.fetch(method, nil)).to_not be_nil
      end

      it "returns the sum of all the #{method} scores" do
        expect(explainer.send(method)).to eq(scores.fetch(method, nil))
      end
    end
  end
end
