---
base_path: "/official-documents"
content_id: e96a1b16-a011-4dc6-9f6a-a54561c4db90
description: Find official documents from government
document_type: finder
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder
title: Official documents
details:
  document_noun: result
  filter:
    has_official_document: true
  show_summaries: true
  sort:
  - name: Most viewed
    key: "-popularity"
  - name: Relevance
    key: "-relevance"
  - name: Updated (newest)
    key: "-public_timestamp"
    default: true
  - name: Updated (oldest)
    key: public_timestamp
  facets:
  - key: release_timestamp
    name: release_timestamp
    short_name: Release date
    preposition: from
    type: date
    display_as_result_metadata: true
    filterable: false
  - key: display_type
    name: content_store_document_type
    short_name: Document type
    preposition: from
    type: text
    display_as_result_metadata: true
    filterable: false
  - key: content_store_document_type
    name: official documents
    type: official_documents
    preposition: Of type
    display_as_result_metadata: true
    filterable: true
    hide_facet_tag: true
  - key: _unused
    filter_key: all_part_of_taxonomy_tree
    keys:
    - level_one_taxon
    - level_two_taxon
    name: topic
    short_name: topic
    type: taxon
    display_as_result_metadata: false
    filterable: true
    preposition: about
  - key: organisations
    name: Organisation
    short_name: Organisation
    preposition: from
    type: text
    show_option_select_filter: true
    display_as_result_metadata: true
    filterable: true
  - key: public_timestamp
    short_name: Updated
    name: Updated
    preposition: Updated
    type: date
    display_as_result_metadata: true
    filterable: true
  default_documents_per_page: 20
routes:
- path: "/official-documents"
  type: exact
- path: "/official-documents.atom"
  type: exact
- path: "/official-documents.json"
  type: exact
