---
base_path: "/search/policy-papers-and-consultations/email-signup"
content_id: 5a4dc517-57cf-4dd6-873f-f1d29f6d540c
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Policy papers and consultations
description: You'll get an email each time content is published.
details:
  email_filter_by:
  subscription_list_title_prefix: Policy papers and consultations
  filter:
    content_purpose_supergroup: policy_and_engagement
  email_filter_facets:
  - facet_id: people
    facet_name: people
  - facet_id: organisations
    facet_name: organisations
  - facet_id: content_store_document_type
    facet_name: document types
    option_lookup:
      policy_papers:
      - impact_assessment
      - case_study
      - policy_paper
      open_consultations:
      - open_consultation
      closed_consultations:
      - closed_consultation
      - consultation_outcome
      open_calls_for_evidence:
      - open_call_for_evidence
      closed_calls_for_evidence:
      - closed_call_for_evidence
      - call_for_evidence_outcome
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: topic
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
routes:
- path: "/search/policy-papers-and-consultations/email-signup"
  type: exact
