---
base_path: "/search/transparency-and-freedom-of-information-releases"
content_id: 9d21cee6-990b-4e87-b254-cada0e2ec4db
description: Find transparency and freedom of information releases from government
signup_content_id: 92f7eb26-030b-4a41-962e-d8e0f8814654
details:
  default_documents_per_page: 20
  document_noun: release
  facets:
  - key: "_unused"
    filter_key: all_part_of_taxonomy_tree
    keys:
    - level_one_taxon
    - level_two_taxon
    name: topic
    short_name: topic
    type: taxon
    display_as_result_metadata: false
    filterable: true
    preposition: about
  - display_as_result_metadata: true
    filterable: true
    key: organisations
    name: Organisation
    preposition: from
    short_name: From
    type: text
    show_option_select_filter: true
  - display_as_result_metadata: true
    filterable: true
    key: world_locations
    name: World location
    preposition: in
    type: text
    show_option_select_filter: true
  - display_as_result_metadata: true
    filterable: true
    key: public_timestamp
    name: Updated
    short_name: Updated
    preposition: Updated
    type: date
  filter:
    content_purpose_supergroup:
    - transparency
  show_summaries: true
  sort:
  - key: "-popularity"
    name: Most viewed
  - key: "-relevance"
    name: Relevance
  - default: true
    key: "-public_timestamp"
    name: Updated (newest)
  - key: public_timestamp
    name: Updated (oldest)
document_type: finder
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder
title: Transparency and freedom of information releases
routes:
- path: "/search/transparency-and-freedom-of-information-releases"
  type: exact
- path: "/search/transparency-and-freedom-of-information-releases.atom"
  type: exact
- path: "/search/transparency-and-freedom-of-information-releases.json"
  type: exact
