---
base_path: "/world/organisations"
content_id: 6c3d2ac3-92e0-4ae7-9705-010fa304fd09
description: A list of British organisations worldwide.
document_type: finder
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder
title: Worldwide organisations
phase: live
details:
  document_noun: organisation
  facets: []
  filter:
    format: worldwide_organisation
  show_summaries: false
  sort:
  - key: title
    name: A-Z
    default: true
  - name: Relevance
    key: "-relevance"
  - name: Updated (newest)
    key: "-public_timestamp"
  - name: Updated (oldest)
    key: public_timestamp
routes:
  - type: exact
    path: "/world/organisations"
  - type: exact
    path: "/world/organisations.json"
  - type: exact
    path: "/world/organisations.atom"
