---
tag: search-api.publishing.service.gov.uk
:concurrency: 5
staging:
  :concurrency:  12
production:
  :concurrency:  12
:require: ./lib/rummager.rb
:queues:
  - default
  - bulk
:limits:
  bulk: 4
  default: 8
