---
tag: search-api.publishing.service.gov.uk
:concurrency: 12
staging:
  :concurrency:  12
production:
  :concurrency:  12
:require: ./lib/rummager.rb
<% if ENV.key?('SIDEKIQ_LOGFILE') %>
:logfile: <%= ENV['SIDEKIQ_LOGFILE'] %>
<% end %>
:queues:
  - default
  - bulk
:limits:
  bulk: 4
  default: 24
