base:
  format:
    coronavirus_landing_page: 2.5
    service_manual_guide: 0.3
    service_manual_topic: 0.3
    transaction: 1.5
    # Should appear below govuk (mainstream) content
    aaib_report: 0.2
    research_for_development_output: 0.2
    hmrc_manual_section: 0.2
    service_standard_report: 0.05
    # Inside Gov formats
    minister: 1.7
    operational_field: 1.5
    organisation: 2.5
    topical_event: 1.5
    # Hide mainstream browse pages
    mainstream_browse_page: 0
  content_store_document_type:
    detailed_guide: 2.5
    document_collection: 2.5
    foi_release: 0.2
    manual: 2.5
    regulation: 2.5
    travel_advice: 2.5
  content_purpose_supergroup:
    services: 2.5
  organisation_state:
    closed: 0.2
    devolved: 0.3
  is_historic:
    true: 0.5
# Overrides to apply to the sitemap priorities in external search
external_search:
  format:
    mainstream_browse_page: 2
    policy: 1.5
    topic: 2
