require 'time'
require 'open-uri'
require 'fileutils'

module HealthCheck
  GID_ALIASES = {
    'mainstream' => 0,
    'government' => 2,
    'detailed' => 3,
    'spelling' => 9
  }

  class Downloader
    def initialize(options = {})
      @data_dir = options[:data_dir]
      @logger = options[:logger] || Logging.logger[self]
    end

    def download(*indices)
      indices.each do |index_name|
        write(
          "#{@data_dir}/#{index_name}-weighted-search-terms.csv",
          fetch_data(url: spreadsheet_url(index_name))
        )
      end

      write(
        "#{@data_dir}/suggestions.csv",
        fetch_data(url: spreadsheet_url('spelling'))
      )
    end

    private

    def spreadsheet_url(tab_alias)
      # Link generated by going to:
      #   File
      #     Publish to the web
      #       Get a link to the published data
      #          then choose CSV
      gid = GID_ALIASES.fetch(tab_alias)
      "https://docs.google.com/spreadsheet/pub?key=0AmD7K4ab1dYrdDR5c2tITTNHRUZqajFTTU8wODAzZ1E&single=true&output=csv&gid=#{gid}"
    end

    def fetch_data(url:)
      data = open(url).read
      @logger.info "Downloaded #{url}"
      data
    end

    def write(filename, data)
      File.open(filename, "wb") do |file|
        file.write(data)
        @logger.info "Wrote #{filename}"
      end
    end
  end
end
