name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:

jobs:
  check-ltr-dependencies:
    name: Check Learn to Rank dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check LTR dependencies install
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y liblapack-dev
          pip install -r ltr/jenkins/requirements-freeze.txt
          pip install -r ltr/scripts/requirements-freeze.txt

  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-cache-dependencies.yaml@add-individual-ci-jobs-non-services

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-lint-ruby.yaml@add-individual-ci-jobs-non-services

  test-ruby:
    name: Test Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/ci-test-ruby.yaml@add-individual-ci-jobs-non-services
    with:
      enableElasticsearch: true
