name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-ltr-dependencies:
    name: Check Learn to Rank dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check LTR dependencies install
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y liblapack-dev
          pip install -r ltr/jenkins/requirements-freeze.txt
          pip install -r ltr/scripts/requirements-freeze.txt
  test:
    name: Test app
    uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@main
    with:
      requiresElasticsearch: true
      requiresRedis: true
      runBrakeman: false
