name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test app
    uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@main
    with:
      requiresElasticsearch: true
      requiresRedis: true
      runBrakeman: false
      
