name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Check LTR dependencies install
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y liblapack-dev
          pip install -r ltr/jenkins/requirements-freeze.txt
          pip install -r ltr/scripts/requirements-freeze.txt
